### ISSUE TITLE
Justify functionspaces for `f0`, `s0` and `n0`

### ISSUE THREAD

**Issue by jorgensd** [ComputationalPhysiology/simcardems#103]
As far as I can tell from the source code: https://github.com/ComputationalPhysiology/simcardems/blob/404aa98c519ed6613e9acd956b44a1575ded9457/src/simcardems/mechanics_model.py#L217-L228
we could use `ufl.as_vector((1,0,0))` etc or `Constant((1,0,0))` to define these variables. 

It is at least overkill to use DG-1, DG-0 would be more appropriate.

**Comment by finsberg** [comment]
This will change when we merge https://github.com/ComputationalPhysiology/simcardems/pull/97.

These functions will be will be the fallback microstructure if non is provided, see https://github.com/ComputationalPhysiology/simcardems/blob/94e611986dc86f8a6689175e9d763f49f7bf4ddf/src/simcardems/geometry.py#L248.. Otherwise the microstructure will be computed using the following methods: 

slab: 
https://github.com/ComputationalPhysiology/cardiac_geometries/blob/main/src/cardiac_geometries/_slab_fibers.py

LV:
https://github.com/ComputationalPhysiology/cardiac_geometries/blob/main/src/cardiac_geometries/_lv_ellipsoid_fibers.py


I think DG-1 one here is a bit arbitrary. However, we would also need to interpolate the microstructure onto the EP mesh see (https://github.com/ComputationalPhysiology/simcardems/blob/finsberg/decoupling-geometry-and-bc/src/simcardems/geometry.py#L280) and so I think we should let these functions live in a function space. I am fine with changing this to either DG0 or CG1

**Comment by jorgensd** [comment]
You can interpolate constant into a function space. I will illustrate this, and several key difference between constant and expression in the code below:
```python
import numpy as np
import time
from dolfin import *

mesh = UnitCubeMesh(10, 10, 10)

V = VectorFunctionSpace(mesh, "Lagrange", 2)
u = Function(V)

c = Constant((1, 3, 4))


start = time.perf_counter()
u.interpolate(c)
end = time.perf_counter()

v = Function(V)
start_v = time.perf_counter()
v.interpolate(Expression(("1", "3", "4"), degree=0))
end_v = time.perf_counter()


print(f"Constant {end-start} Expression {end_v-start_v}")

assert np.allclose(v.vector()[:], u.vector()[:])
```
In this code, we compare the performance of interpolating an expression or a constant into a function space.
At the first run we get the following timings:
```bash
fenics@dokken-XPS-9320:/root/shared$ python3 mwe_old.py 
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Constant 0.0065713390067685395 Expression 1.5493103100016015
```
At the second run we get:
```bash
fenics@dokken-XPS-9320:/root/shared$ python3 mwe_old.py 
Constant 0.006256181004573591 Expression 0.007620492993737571
```
The explanation for the huge difference in time is that you have to compile C++ code for interpolation of the expression, which is not required for the constant.

In turn, say that we want to use the result of `f0` in interpolation of a function.
Adding
```python
Q = VectorFunctionSpace(mesh, "DG", 1)
q = Function(Q)
start_q = time.perf_counter()
q.interpolate(c)
end_q = time.perf_counter()
q2 = Function(Q)
start_2 = time.perf_counter()
q2.interpolate(v)
end_2 = time.perf_counter()

print(f"Constant {end_q-start_q} Function {end_2-start_2}")

assert np.allclose(q.vector()[:], q2.vector()[:])
```
yields the result for first run:
```bash
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Constant 0.0026777800085255876 Function 1.2271704119921196
```
Second run:
```bash
Constant 0.002801103997626342 Function 1.320239737004158
```
As you can see, you do not get any improvement on second run after caching when it comes to function interpolation.
